Convert warning to error

diff --git a/.github/workflows/repo-sync-for-app.yml b/.github/workflows/repo-sync-for-app.yml
--- a/.github/workflows/repo-sync-for-app.yml
+++ b/.github/workflows/repo-sync-for-app.yml
@@ -155,9 +155,11 @@ jobs:
           ARM_USE_AZUREAD: true
           ARM_USE_OIDC: true
 
-      - name: Issue Warning
+      - name: Issue Error
         if: always() && hashFiles('issue.log.json') != ''
-        run: echo "::warning title=${{ matrix.repoId }} has issues::Check the log file artifact for ${{ matrix.repoId }} to see the details."
+        run: |
+          echo "::error title=${{ matrix.repoId }} has issues::Check the log file artifact for ${{ matrix.repoId }} to see the details."
+          exit 1
 
       - name: Upload Issue Logs Json
         if: always() && hashFiles('issue.log.json') != ''
